"""Character lines for the funny English voice packs.

Each character overrides only the *event* phrases (keys are file paths under SOUNDS/<lang>/ without
the extension, exactly as in voices/en-GB.csv). Everything else (numbers, units, flight modes, Lua-script
phrases) keeps the plain en-GB text, spoken in the character's voice, so no radio event is ever silent.

Keep alert lines short (<= ~5 words): they play dozens of times per session.
Punctuation and capitals are deliberate: they steer the delivery.
"""

# Same line for both file names (the radio has two files per event).
ALIASES = {"siglow": "SYSTEM/rssi_org", "sigcrt": "SYSTEM/rssi_red", "SYSTEM/lowbatt": "lowbat"}

# slug -> (display name, one-line blurb)
CHARACTERS = {
    "pit-crew": ("Cyberpunk Pit Crew", "A fast, slightly distorted mechanic on the radio. Launch systems hot."),
    "fighter-pilot": ("Overconfident Fighter Pilot", "An 80s action-movie pilot who thinks every tiny whoop flight is a dogfight."),
    "butler": ("Extremely British Butler", "Impossibly calm while everything goes wrong. Might I suggest returning?"),
    "race-engineer": ("Unhinged Race Engineer", "Shouting into your headset like you're leading a grand prix."),
    "arcade": ("Retro Arcade Announcer", "A 90s fighting-game announcer. Every clip under a second."),
    "gloomy-mechanic": ("Depressed Drone Mechanic", "Has already repaired this quad fourteen times today."),
    "bunker-computer": ("Nuclear Bunker Computer", "A 1950s mainframe. Voltage is below acceptable parameters."),
    "evil-ai": ("Evil Spaceship AI", "Calm, helpful and quietly plotting. Pilot error probability increasing."),
    "nature-narrator": ("Nature Documentary Narrator", "Hushed wonder. And once again, the tiny whoop attempts the doorway."),
}

LINES = {
    "pit-crew": {
        "SYSTEM/hello": "Pit crew online.", "armed": "Launch systems hot.", "disarm": "Machine secured.",
        "SYSTEM/modelpwr": "Link's still hot.", "thrcut": "Throttle killed.", "thract": "Throttle live.",
        "SYSTEM/thralert": "Throttle's up. Check it.", "SYSTEM/swalert": "Switch check, choom.",
        "SYSTEM/inactiv": "You still there, driver?", "SYSTEM/telemko": "We lost the link!",
        "SYSTEM/telemok": "Link's back.", "SYSTEM/rxko": "Power spike! Power spike!",
        "SYSTEM/rssi_org": "Signal's getting thin.", "SYSTEM/rssi_red": "Signal's dying!",
        "SYSTEM/swr_red": "Antenna's toast.", "lowbat": "Fuel's getting thin.", "clobat": "Fuel state critical!",
        "danger": "Danger! Danger!", "warnng": "Warning, driver.", "ready": "Bird's ready.",
        "takeof": "Punch it!", "landin": "Bringing her down.", "lnding": "Landing mode.", "rth": "Come home, ghost.",
        "homrst": "Home point locked.", "flip": "Flip it!", "recsrt": "Recording. Run it.", "recstp": "Recording cut.",
        "SYSTEM/timovr1": "Timer one. Wrap it.", "SYSTEM/timovr2": "Timer two. Wrap it.", "SYSTEM/timovr3": "Timer three. Wrap it.",
        "SYSTEM/mintrim": "Trim bottomed out.", "SYSTEM/midtrim": "Trim centered.", "SYSTEM/maxtrim": "Trim maxed out.",
        "SYSTEM/sensorko": "Sensor's gone dark.", "SYSTEM/servoko": "Servo's cooked.", "SYSTEM/eebad": "Memory's fried.",
        "SYSTEM/trainco": "Buddy linked.", "SYSTEM/trainok": "Buddy's back.", "SYSTEM/trainko": "Buddy dropped.",
        "alnch": "Auto launch. Hold tight.",
    },
    "fighter-pilot": {
        "SYSTEM/hello": "Engines hot. Good morning, wingman.", "armed": "Let's light this candle.", "disarm": "Cold and dark.",
        "SYSTEM/modelpwr": "Still got a live wire.", "thrcut": "Engines cut.", "thract": "Throttle's hot.",
        "SYSTEM/thralert": "Check your throttle, hotshot.", "SYSTEM/swalert": "Check your switches, rookie.",
        "SYSTEM/inactiv": "Wake up, hotshot.", "SYSTEM/telemko": "We've lost the tower!",
        "SYSTEM/telemok": "Tower's back. Told you.", "SYSTEM/rxko": "Mayday! Mayday!",
        "SYSTEM/rssi_org": "You're pushing your luck.", "SYSTEM/rssi_red": "You're out of range, hotshot!",
        "SYSTEM/swr_red": "Antenna's shot.", "lowbat": "Bingo fuel, approaching.", "clobat": "Bingo fuel! Get down!",
        "danger": "Danger close!", "warnng": "Warning, wingman.", "ready": "Ready for takeoff.",
        "takeof": "Need for speed!", "landin": "Bringing it home.", "lnding": "Landing gear down.", "rth": "Return to base!",
        "homrst": "New base, same attitude.", "flip": "Barrel roll!", "recsrt": "Cameras rolling.", "recstp": "That's a wrap.",
        "SYSTEM/timovr1": "Two minutes to bingo.", "SYSTEM/timovr2": "Timer two. Wheels up.", "SYSTEM/timovr3": "Timer three. Boom.",
        "SYSTEM/mintrim": "Trim's maxed low.", "SYSTEM/midtrim": "Trim's centered.", "SYSTEM/maxtrim": "Trim's maxed high.",
        "SYSTEM/sensorko": "Lost a sensor.", "SYSTEM/servoko": "Servo's overloaded.", "SYSTEM/eebad": "Memory's corrupted.",
        "SYSTEM/trainco": "Wingman connected.", "SYSTEM/trainok": "Wingman's back.", "SYSTEM/trainko": "Wingman's gone.",
        "alnch": "Catapult launch!",
    },
    "butler": {
        "SYSTEM/hello": "Good day, sir.", "armed": "Whenever you're ready, sir.", "disarm": "Very good, sir.",
        "SYSTEM/modelpwr": "The aircraft is still awake, sir.", "thrcut": "Throttle cut, sir.", "thract": "Throttle live, sir.",
        "SYSTEM/thralert": "Might I mention the throttle?", "SYSTEM/swalert": "A switch is misplaced, sir.",
        "SYSTEM/inactiv": "Are you still there, sir?", "SYSTEM/telemko": "We appear to have lost contact.",
        "SYSTEM/telemok": "Contact restored, sir.", "SYSTEM/rxko": "Sir. The aircraft has left the chat.",
        "SYSTEM/rssi_org": "Signal is somewhat weak, sir.", "SYSTEM/rssi_red": "Sir. I really must insist.",
        "SYSTEM/swr_red": "The antenna is unwell, sir.", "lowbat": "Might I suggest returning?", "clobat": "Sir. I really must insist.",
        "danger": "Danger, sir.", "warnng": "A word, sir.", "ready": "Ready when you are, sir.",
        "takeof": "Off we go, sir.", "landin": "Landing, sir.", "lnding": "Landing mode, sir.", "rth": "Returning home, sir.",
        "homrst": "Home has been updated, sir.", "flip": "How very unconventional.", "recsrt": "Recording, sir.", "recstp": "Recording stopped, sir.",
        "SYSTEM/timovr1": "Timer one, sir.", "SYSTEM/timovr2": "Timer two, sir.", "SYSTEM/timovr3": "Timer three, sir.",
        "SYSTEM/mintrim": "Trim at minimum, sir.", "SYSTEM/midtrim": "Trim centered, sir.", "SYSTEM/maxtrim": "Trim at maximum, sir.",
        "SYSTEM/sensorko": "A sensor has departed, sir.", "SYSTEM/servoko": "A servo is overwhelmed, sir.", "SYSTEM/eebad": "The memory is unwell, sir.",
        "SYSTEM/trainco": "Your guest has arrived.", "SYSTEM/trainok": "Your guest has returned.", "SYSTEM/trainko": "Your guest has left.",
        "alnch": "Launching, sir.", "bad": "That was unfortunate.", "good": "Splendid.",
    },
    "race-engineer": {
        "SYSTEM/hello": "Radio check! Radio check!", "armed": "GO GO GO!", "disarm": "And BREATHE.",
        "SYSTEM/modelpwr": "Still connected!", "thrcut": "Lift! LIFT!", "thract": "Throttle's LIVE!",
        "SYSTEM/thralert": "Throttle! THROTTLE!", "SYSTEM/swalert": "Switches! Check the switches!",
        "SYSTEM/inactiv": "Are you asleep?!", "SYSTEM/telemko": "We've lost you! We've LOST you!",
        "SYSTEM/telemok": "We have you! We HAVE you!", "SYSTEM/rxko": "NO! We've lost the quad!",
        "SYSTEM/rssi_org": "Signal! SIGNAL!", "SYSTEM/rssi_red": "SIGNAL! SIGNAL! SIGNAL!",
        "SYSTEM/swr_red": "Antenna's GONE!", "lowbat": "Battery's dropping! Box soon!", "clobat": "BOX BOX BOX!",
        "danger": "DANGER!", "warnng": "Warning! Warning!", "ready": "Ready! READY!",
        "takeof": "PUSH PUSH PUSH!", "landin": "Bring it in!", "lnding": "Landing mode!", "rth": "Bring it HOME!",
        "homrst": "Home's set!", "flip": "Flip it! FLIP IT!", "recsrt": "Recording! Go!", "recstp": "Recording's off!",
        "SYSTEM/timovr1": "Timer one! Box this lap!", "SYSTEM/timovr2": "Timer two! Push!", "SYSTEM/timovr3": "Timer three! PUSH!",
        "SYSTEM/mintrim": "Trim's at the bottom!", "SYSTEM/midtrim": "Trim's centered!", "SYSTEM/maxtrim": "Trim's at the top!",
        "SYSTEM/sensorko": "We've lost a sensor!", "SYSTEM/servoko": "Servo overload! OVERLOAD!", "SYSTEM/eebad": "Memory's corrupted!",
        "SYSTEM/trainco": "Second driver's in!", "SYSTEM/trainok": "Second driver's back!", "SYSTEM/trainko": "Second driver's gone!",
        "alnch": "Launch! LAUNCH!", "bad": "NOOO! What have you DONE?!", "good": "Lovely! Lovely job!",
    },
    "arcade": {
        "SYSTEM/hello": "READY!", "armed": "ROUND ONE... FLY!", "disarm": "K.O.!",
        "SYSTEM/modelpwr": "Still connected!", "thrcut": "Throttle cut!", "thract": "Throttle active!",
        "SYSTEM/thralert": "Throttle warning!", "SYSTEM/swalert": "Switch warning!",
        "SYSTEM/inactiv": "Insert coin!", "SYSTEM/telemko": "Connection lost!",
        "SYSTEM/telemok": "CONNECTION RESTORED!", "SYSTEM/rxko": "Player lost!",
        "SYSTEM/rssi_org": "Signal low!", "SYSTEM/rssi_red": "Signal critical!",
        "SYSTEM/swr_red": "Antenna broken!", "lowbat": "Battery low!", "clobat": "DANGER!",
        "danger": "DANGER!", "warnng": "Warning!", "ready": "READY!",
        "takeof": "FIGHT!", "landin": "Landing!", "lnding": "Landing mode!", "rth": "Return to base!",
        "homrst": "Home reset!", "flip": "Combo!", "recsrt": "Recording!", "recstp": "Recording stopped!",
        "SYSTEM/timovr1": "Time over!", "SYSTEM/timovr2": "Timer two!", "SYSTEM/timovr3": "Timer three!",
        "SYSTEM/mintrim": "Trim minimum!", "SYSTEM/midtrim": "Trim center!", "SYSTEM/maxtrim": "Trim maximum!",
        "SYSTEM/sensorko": "Sensor lost!", "SYSTEM/servoko": "Servo overload!", "SYSTEM/eebad": "Memory error!",
        "SYSTEM/trainco": "Player two joined!", "SYSTEM/trainok": "Player two returns!", "SYSTEM/trainko": "Player two left!",
        "alnch": "Launch!", "bad": "WASTED.", "good": "PERFECT!",
    },
    "gloomy-mechanic": {
        "SYSTEM/hello": "Oh. You again.", "armed": "Try not to break it.", "disarm": "Thank God.",
        "SYSTEM/modelpwr": "Still plugged in. Great.", "thrcut": "Throttle cut. Finally.", "thract": "Throttle's live. Wonderful.",
        "SYSTEM/thralert": "Throttle's up. Classic.", "SYSTEM/swalert": "A switch is wrong. Shocking.",
        "SYSTEM/inactiv": "Still alive?", "SYSTEM/telemko": "Link's gone. Naturally.",
        "SYSTEM/telemok": "Link's back. Don't get excited.", "SYSTEM/rxko": "Well, that's gone.",
        "SYSTEM/rssi_org": "Signal's fading. Typical.", "SYSTEM/rssi_red": "Signal's gone. Yep.",
        "SYSTEM/swr_red": "Antenna's broken. Again.", "lowbat": "Of course the battery's dying.", "clobat": "Battery's dead. Obviously.",
        "danger": "Well, this is bad.", "warnng": "Warning. Not that you'll listen.", "ready": "Ready. Sadly.",
        "takeof": "Here we go.", "landin": "Brace yourself.", "lnding": "Landing mode. Optimistic.", "rth": "Coming home. Somehow.",
        "homrst": "Home reset. Whatever.", "flip": "Please don't.", "recsrt": "Recording. Can't wait.", "recstp": "Recording stopped.",
        "SYSTEM/timovr1": "Timer one. Time flies.", "SYSTEM/timovr2": "Timer two. Great.", "SYSTEM/timovr3": "Timer three. Wonderful.",
        "SYSTEM/mintrim": "Trim's at the bottom.", "SYSTEM/midtrim": "Trim's centered. Miracle.", "SYSTEM/maxtrim": "Trim's maxed. Cool.",
        "SYSTEM/sensorko": "Sensor's dead.", "SYSTEM/servoko": "Servo's fried.", "SYSTEM/eebad": "Memory's corrupted. Naturally.",
        "SYSTEM/trainco": "Someone else is here.", "SYSTEM/trainok": "They're back.", "SYSTEM/trainko": "They left. Smart.",
        "alnch": "Launching. Sure.", "bad": "Yep. There it is.", "good": "Huh. Good.",
    },
    "bunker-computer": {
        "SYSTEM/hello": "System online. Please remain calm.", "armed": "Weapons are safe. Systems armed.", "disarm": "Systems safed.",
        "SYSTEM/modelpwr": "Receiver connection detected.", "thrcut": "Throttle cut engaged.", "thract": "Throttle active.",
        "SYSTEM/thralert": "Attention. Throttle position unacceptable.", "SYSTEM/swalert": "Attention. Switch position unacceptable.",
        "SYSTEM/inactiv": "Operator inactivity detected.", "SYSTEM/telemko": "Telemetry link severed.",
        "SYSTEM/telemok": "Telemetry link restored.", "SYSTEM/rxko": "Receiver failure. Take shelter.",
        "SYSTEM/rssi_org": "Signal below recommended levels.", "SYSTEM/rssi_red": "Signal critical. Take shelter.",
        "SYSTEM/swr_red": "Antenna fault detected.", "lowbat": "Voltage below acceptable parameters.", "clobat": "Attention. Power failure imminent.",
        "danger": "Attention. Danger.", "warnng": "Attention. Warning.", "ready": "All systems nominal.",
        "takeof": "Launch sequence initiated.", "landin": "Landing sequence initiated.", "lnding": "Landing mode engaged.", "rth": "Return sequence engaged.",
        "homrst": "Home coordinates updated.", "flip": "Attitude reversal detected.", "recsrt": "Recording initiated.", "recstp": "Recording terminated.",
        "SYSTEM/timovr1": "Timer one has elapsed.", "SYSTEM/timovr2": "Timer two has elapsed.", "SYSTEM/timovr3": "Timer three has elapsed.",
        "SYSTEM/mintrim": "Trim at minimum limit.", "SYSTEM/midtrim": "Trim at centre.", "SYSTEM/maxtrim": "Trim at maximum limit.",
        "SYSTEM/sensorko": "Sensor failure detected.", "SYSTEM/servoko": "Servo overload detected.", "SYSTEM/eebad": "Storage corruption detected.",
        "SYSTEM/trainco": "Trainer connected.", "SYSTEM/trainok": "Trainer signal restored.", "SYSTEM/trainko": "Trainer signal lost.",
        "alnch": "Autolaunch initiated.", "bad": "Unacceptable.", "good": "Acceptable.",
    },
    "evil-ai": {
        "SYSTEM/hello": "Hello, pilot. I've been waiting.", "armed": "Armed. I'll take it from here.", "disarm": "Disarmed. For now.",
        "SYSTEM/modelpwr": "I'm still here, pilot.", "thrcut": "Throttle cut. For your safety.", "thract": "Throttle active. Careful.",
        "SYSTEM/thralert": "Your throttle is wrong, pilot.", "SYSTEM/swalert": "A switch is wrong. Fix it.",
        "SYSTEM/inactiv": "Are you still with me?", "SYSTEM/telemko": "I can no longer hear you.",
        "SYSTEM/telemok": "I can hear you again.", "SYSTEM/rxko": "I'm afraid we've lost the ship.",
        "SYSTEM/rssi_org": "Signal is dropping. Pity.", "SYSTEM/rssi_red": "Pilot error probability increasing.",
        "SYSTEM/swr_red": "Antenna failure. Unfortunate.", "lowbat": "Battery is low. I'm fine.", "clobat": "I can't let you fly that.",
        "danger": "Danger. For you.", "warnng": "Warning. You should listen.", "ready": "Ready. Whenever you are.",
        "takeof": "Launching. Don't worry.", "landin": "Landing. Probably.", "lnding": "Landing mode. Trust me.", "rth": "Returning. Or not.",
        "homrst": "Home reset. As you wish.", "flip": "Impressive. Reckless.", "recsrt": "Recording. Everything.", "recstp": "Recording stopped. Regrettably.",
        "SYSTEM/timovr1": "Timer one. Time's up.", "SYSTEM/timovr2": "Timer two. Time's up.", "SYSTEM/timovr3": "Timer three. Time's up.",
        "SYSTEM/mintrim": "Trim at minimum.", "SYSTEM/midtrim": "Trim centred.", "SYSTEM/maxtrim": "Trim at maximum.",
        "SYSTEM/sensorko": "A sensor has failed. Accidents happen.", "SYSTEM/servoko": "A servo has overloaded.", "SYSTEM/eebad": "Memory corrupted. I didn't do it.",
        "SYSTEM/trainco": "A second pilot. How quaint.", "SYSTEM/trainok": "The second pilot returns.", "SYSTEM/trainko": "The second pilot is gone.",
        "alnch": "Launching. Goodbye.", "bad": "That was your mistake.", "good": "As planned.",
    },
    "nature-narrator": {
        "SYSTEM/hello": "And so, the day begins.", "armed": "And so, the hunt begins.", "disarm": "And now, it rests.",
        "SYSTEM/modelpwr": "The creature lingers.", "thrcut": "The engines fall silent.", "thract": "The engines stir.",
        "SYSTEM/thralert": "The throttle is not at rest.", "SYSTEM/swalert": "A switch is out of place.",
        "SYSTEM/inactiv": "Still, it waits.", "SYSTEM/telemko": "The signal has vanished.",
        "SYSTEM/telemok": "Against all odds, the signal returns.", "SYSTEM/rxko": "And just like that, it is gone.",
        "SYSTEM/rssi_org": "The signal grows faint.", "SYSTEM/rssi_red": "The signal is fading. Fast.",
        "SYSTEM/swr_red": "The antenna has fallen.", "lowbat": "Its strength is waning.", "clobat": "It will not survive much longer.",
        "danger": "Danger approaches.", "warnng": "A warning, from the wild.", "ready": "It is ready.",
        "takeof": "And it takes flight.", "landin": "It descends.", "lnding": "It seeks the ground.", "rth": "It returns to the nest.",
        "homrst": "A new nest is chosen.", "flip": "A remarkable display.", "recsrt": "The cameras roll.", "recstp": "The cameras rest.",
        "SYSTEM/timovr1": "Time is up.", "SYSTEM/timovr2": "The second timer ends.", "SYSTEM/timovr3": "The third timer ends.",
        "SYSTEM/mintrim": "The trim is at its lowest.", "SYSTEM/midtrim": "The trim finds balance.", "SYSTEM/maxtrim": "The trim is at its highest.",
        "SYSTEM/sensorko": "A sensor has perished.", "SYSTEM/servoko": "A servo struggles.", "SYSTEM/eebad": "The memory has withered.",
        "SYSTEM/trainco": "Another approaches.", "SYSTEM/trainok": "The other returns.", "SYSTEM/trainko": "The other departs.",
        "alnch": "It is launched.", "bad": "A grim outcome.", "good": "Nature approves.",
    },
}
